name: CI for API

on:
  push:
    branches:
      - main  # Déclenche l'action sur un push vers la branche `main`
  pull_request:
    branches:
      - main  # Déclenche l'action sur une pull request vers la branche `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Utiliser une image Ubuntu pour exécuter le job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clone le dépôt

    - name: Set up Python
      uses: actions/setup-python@v2  # Configure Python
      with:
        python-version: '3.9'  # Choisis la version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installer les dépendances

    - name: Run tests with pytest
      run: |
        pytest check_api.py  # Exécute les tests
