name: CI for API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Utiliser une machine virtuelle Ubuntu pour exécuter le job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clone le dépôt

    - name: Set up Python
      uses: actions/setup-python@v2  # Configure Python
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installer les dépendances

    - name: Start API in the background
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &  # Lance l'API en arrière-plan

    - name: Wait for the API to be ready
      run: |
        until curl -s http://localhost:8000/status; do
          echo "Waiting for API to be ready..."
          sleep 5
        done

    - name: Run tests with pytest
      run: |
        pytest check_api.py  # Exécute les tests

