name: CI for API

on:
  push:
    branches:
      - main  # Déclenche l'action sur la branche `main` lors d'un push
  pull_request:
    branches:
      - main  # Déclenche l'action lors de la création d'une pull request sur `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Utiliser une image Ubuntu pour exécuter les tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Cloner ton dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Version de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install -r requirements.txt  # Installer les dépendances de ton projet

    - name: Run tests with pytest
      run: |
        pytest check_api.py  # Exécuter les tests

